---
title: "C elegans scRNA-seq"
output: html_document
date: "2023-06-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Seurat)
library(SeuratDisk)
```

## R Markdown

I read it in on the cluster using the anndata package
w <- anndata::read_h5ad("ad_worm_aging.h5ad")




```{r QC}
#To load the Seurat object:
worms <- LoadH5Seurat("D:/Harry_Jones/scRNA_Celegans/data/worms.h5Seurat")
# Only running this once as it takes a while
#==========
# Some QC
#==========
# for human and mouse we can identify mitochondrial genes  (prefixed with "MT").
# C elegans MT genes are named differently 
# From WormBase parasite
# https://parasite.wormbase.org/biomart/martview/a635bf7189ad83f47d6778648d67fd2e
mt_genes <- c("ctb-1","nduo-6","ndfl-4","nduo-1","atp-6","nduo-2","ctc-3","nduo-4",
							"ctc-1","ctc-2","nduo-3","nduo-5","MTCE.1","MTCE.2","MTCE.5","MTCE.6",
							"MTCE.7","MTCE.8","MTCE.9","MTCE.10","MTCE.13","MTCE.14","MTCE.15",
							"MTCE.17","MTCE.18","MTCE.19","MTCE.20","MTCE.22","MTCE.24","MTCE.27",
							"MTCE.28","MTCE.29","MTCE.30","MTCE.32","MTCE.33","MTCE.36")

mt_genes <- mt_genes[mt_genes %in% rownames(worms@assays$RNA@counts)]
worms$percent.MT <- PercentageFeatureSet(worms, features = mt_genes)

# rrn seems to be ribosomal rRNA
grep("^rrn",rownames(worms@assays$RNA@counts),value = TRUE) # there may be more than these 3 but we'll go with this for now
worms$percent.Ribosomal <- PercentageFeatureSet(worms, pattern="^rrn")

# https://www.bioinformatics.babraham.ac.uk/training/10XRNASeq/seurat_workflow.html#QC
worms$largest_count <- apply(
	worms@assays$RNA@counts,
	2,
	max
)

worms$largest_index <- apply(
	worms@assays$RNA@counts,
	2,
	which.max
)

worms$largest_gene <- rownames(worms)[worms$largest_index] 
worms$percent.Largest.Gene <- 100 * worms$largest_count/worms$nCount_RNA

save(worms, file="data/worms1.rds")

```

### QC plots

```{r}
# VlnPlot(
# 	worms, 
# 	features = c("nCount_RNA", "nFeature_RNA", "percent.MT", "percent.Ribosomal", "percent.Largest.Gene"),
# 	cols =c("red", "blue2")
# )

VlnPlot(
	worms, 
	features = c("nCount_RNA", "nFeature_RNA", "percent.MT", "percent.Ribosomal", "percent.Largest.Gene"),
	pt.size=0
) +
scale_y_log10()

#hist(worms$percent.Largest.Gene)


```

```{r}
qc.metrics <- as_tibble(
	worms[[]],
	rownames="Cell.Barcode"
) 

head(qc.metrics)
```

```{r}
qc.metrics %>%
	arrange(percent.MT) %>%
	ggplot(aes(nCount_RNA,nFeature_RNA,colour=percent.MT)) + 
	geom_point() + 
	scale_color_gradientn(colors=c("black","blue","green2","red","yellow")) +
	ggtitle("QC metrics") +
	geom_hline(yintercept = 100) +
	geom_hline(yintercept = 2500) +
	scale_x_log10() + scale_y_log10()

qc.metrics  <- qc.metrics %>%
	mutate(complexity=log10(nFeature_RNA) / log10(nCount_RNA))  
```


### Complexity

```{r}
complexity.lm <- lm(log10(qc.metrics$nFeature_RNA)~log10(qc.metrics$nCount_RNA))

complexity.lm

qc.metrics <- qc.metrics %>%
	mutate(
		complexity_diff = log10(nFeature_RNA) - ((log10(qc.metrics$nCount_RNA)*complexity.lm$coefficients[2])+complexity.lm$coefficients[1])
	)

qc.metrics %>%
	ggplot(aes(x=complexity_diff)) +
	geom_density(fill="seagreen")

complexity_scale <- min(c(max(qc.metrics$complexity_diff),0-min(qc.metrics$complexity_diff))) 

qc.metrics %>%
	mutate(complexity_diff=replace(complexity_diff,complexity_diff< -0.1,-0.1)) %>%
	ggplot(aes(x=log10(nCount_RNA), y=log10(nFeature_RNA), colour=complexity_diff)) +
	geom_point(size=0.5) +
	geom_abline(slope=complexity.lm$coefficients[2], intercept = complexity.lm$coefficients[1]) +
	scale_colour_gradient2(low="blue2",mid="grey",high="red2")

qc.metrics %>%
	ggplot(aes(x=complexity_diff, y=percent.Largest.Gene)) +
	geom_point() 
```


```{r}
largest_gene_list <- qc.metrics %>%
	group_by(largest_gene) %>%
	count() %>%
	arrange(desc(n)) 

largest_gene_list

largest_gene_list %>%
	filter(n>814) %>%
	pull(largest_gene) -> largest_genes_to_plot

qc.metrics %>%
	filter(largest_gene %in% largest_genes_to_plot) %>%
	mutate(largest_gene=factor(largest_gene, levels=largest_genes_to_plot)) %>%
	arrange(largest_gene) %>%
	ggplot(aes(x=log10(nCount_RNA), y=log10(nFeature_RNA), colour=largest_gene)) +
	geom_point(size=1) +
	scale_colour_manual(values=c("black",RColorBrewer::brewer.pal(9,"Set1")))

qc.metrics %>%
	filter(largest_gene %in% largest_genes_to_plot) %>%
	mutate(largest_gene=factor(largest_gene, levels=largest_genes_to_plot)) %>%
	arrange(largest_gene) %>%
	ggplot(aes(x=complexity_diff, y=percent.Largest.Gene, colour=largest_gene)) +
	geom_point()+
	scale_colour_manual(values=c("black",RColorBrewer::brewer.pal(9,"Set1")))

qc.metrics %>%
	arrange(percent.MT) %>%
	ggplot(aes(x=complexity_diff, y=percent.Largest.Gene, colour=percent.MT)) +
	geom_point() +
	scale_colour_gradient(low="grey", high="red2")

# doesn't look like MT genes are a big problem

qc.metrics %>%
	arrange(percent.Ribosomal) %>%
	ggplot(aes(x=complexity_diff, y=percent.Largest.Gene, colour=percent.Ribosomal)) +
	geom_point() +
	scale_colour_gradient(low="grey", high="red2")

qc.metrics %>%
	ggplot(aes(percent.MT)) + 
	geom_histogram(binwidth = 0.3, fill="seagreen", colour="black") +
	ggtitle("Distribution of Percentage Mitochondrion") +
	geom_vline(xintercept = 8)

qc.metrics %>%
	ggplot(aes(percent.Largest.Gene)) + 
	geom_histogram(binwidth = 0.7, fill="seagreen", colour="black") +
	ggtitle("Distribution of Percentage Largest Gene") +
	geom_vline(xintercept = 30)

qc.metrics %>%
	ggplot(aes(nFeature_RNA)) + 
	geom_histogram(fill="seagreen", binwidth = 50, colour="black") +
	ggtitle("Distribution of nFeature_RNA") +
	geom_vline(xintercept = 2500) +
	geom_vline(xintercept = 100)

qc.metrics %>%
	ggplot(aes(x = timepoint, y=nFeature_RNA)) + 
	geom_violin(fill="seagreen", colour="black") +
	ggtitle("Distribution of nFeature_RNA") 

qc.metrics %>%
	ggplot(aes(x = timepoint, y=nFeature_RNA)) + 
	geom_violin(fill="seagreen", colour="black") +
	ggtitle("Distribution of nFeature_RNA") +
	scale_y_log10() +
	geom_hline(yintercept = c(100, 2500))


```
## Filtering 

```{r}
# Relaxed filtering so that we don't remove too much data that is potentially of interest.
worms <- subset(
	worms,
	nFeature_RNA>100 &
		nFeature_RNA < 2500 &
		percent.MT < 8 &
		percent.Largest.Gene < 40
)

```


## Normalisation

```{r, eval =FALSE}
# way too many 0 values to use the simple normalisation
# Normalise again, this time using a centered log ratio transformation - 
# more similar to the sort of size factor based normalisation which is used for many RNA-Seq experiments. The margin=2 option means that it normalises per cell instead of per gene
worms <- NormalizeData(worms, normalization.method = "CLR", margin = 2)
save(worms, file = "data/clr_norm_worms_lax.rds")
```

```{r}
as_tibble(
	worms@assays$RNA@data[,1:100]
) %>%
	pivot_longer(
		cols=everything(),
		names_to="cell",
		values_to="expression"
	) %>%
	ggplot(aes(x=expression, group=cell)) +
	geom_density() +
	coord_cartesian(ylim=c(0,0.6), xlim=c(0,3))
# That looks better

normalisation.qc <- tibble(
	pc95 = apply(worms[["RNA"]]@data,2,quantile,0.95),
	measured = apply(worms[["RNA"]]@data,2,function(x)(100*sum(x!=0))/length(x))
) 

normalisation.qc %>% 
	ggplot(aes(x=measured,y=pc95))+
	geom_point()+
	ggtitle("Normalisation of data")

```

```{r}
worms <- ScaleData(worms,features=rownames(data))
save(worms, file = "data/clr_norm_scaled_worms_lax.rds")
```

